### ISSUE TITLE
Download datasets error

### ISSUE THREAD

**Issue by ghying** [codeslake/RefVSR#10]
Hi, I download the dataset, but they both fail in the middle stage and prompt unknown server error. Could you please check the download link and ensure they are properly downloaded.

**Comment by ZifanCui** [comment]
I had the same problem

**Comment by codeslake** [comment]
Do all links (dropbox/one drive/google drive) fail?
If one fails, you can try the other ones.

Please let me know. I will reduce the size of each zip file.

**Comment by ZifanCui** [comment]
> I tried Google drive and dropbox both failed. Google drive will failed when the download reaches 20G~30G

**Comment by codeslake** [comment]
Thanks for bringing it to my attention.
I will update the dataset links.
Try [this link](https://drive.google.com/open?id=1-zBRkqAUk7VihH9AdX43T3J4r3vt3DD-&authuser=codeslake%40gmail.com&usp=drive_fs) to download the dataset. Each zip partition has a size of 10GB.

**Comment by ZifanCui** [comment]
> Thanks for bringing it to my attention. I will update the dataset links. Try [this link](https://drive.google.com/open?id=1-zBRkqAUk7VihH9AdX43T3J4r3vt3DD-&authuser=codeslake%40gmail.com&usp=drive_fs) to download the dataset. Each zip partition has a size of 10GB.

This link requires permission to access.

**Comment by ghying** [comment]
I download the datasets successfully. Use the OneDriver link and download it with IDM plugin.

**Comment by codeslake** [comment]
Great! thanks for sharing :)

**Comment by LokiXun** [comment]
> Thanks for bringing it to my attention. I will update the dataset links. Try [this link](https://drive.google.com/open?id=1-zBRkqAUk7VihH9AdX43T3J4r3vt3DD-&authuser=codeslake%40gmail.com&usp=drive_fs) to download the dataset. Each zip partition has a size of 10GB.

Hi this link shows `ERROR 404`, and the dropbox links can not download successfully. Any solutions for this
