### ISSUE TITLE
Difficulties withe the configuration file

### ISSUE THREAD

**Issue by Maxibugg** [codeslake/RefVSR#14]
Hello there,

I'm a begginer programmer trying to reproduce your result. However, i met some difficulties wich i think comme from the dataset.

here is my branche organisation after extracting the .zip :

RefVSR
    ├── evaluation
    ├──install
    ├──ckpt
    ├──...
    ├──DATA_OFFSET
               ├── source
               ├──target
               ├──RealMCVSR.z01
               ├──    ...
               ├──RealMCVSR.z21

i have finally run this scipt :   /scripts_eval/eval_RefVSR_MFID_8K.sh with the following configuration
![image](https://github.com/codeslake/RefVSR/assets/98988026/3e9a64d4-3441-4b73-ac55-4ddb3707a841)

And here is the error message :
![image](https://github.com/codeslake/RefVSR/assets/98988026/39bcedf6-6289-4ccf-b934-0e7f5a940cf8)

Could you help or give me another direction to resolve my bug ?

your faithfully, 

Maxx

**Comment by renaissanceee** [comment]
Hi, how did you organize the dataset? I'm not sure about source/target in RealDOF. What;s the meaning of RealDOF?
