### ISSUE TITLE
About evaluation results

### ISSUE THREAD

**Issue by 1180300419** [codeslake/RefVSR#3]
I have downloaded the pre-trained models as well as dataset from the given links and tried to run the evaluation scripts( I didn't modify any hyperparameters except for the dataset path and log path ). However, there's a large gap between my evaluation results and those in the paper.

So I would like to ask what is the problem and what should I try to get the results in the paper?

Thank you!

**Comment by codeslake** [comment]
Hi, Xiaohui.

Thank you for pointing this out.
When modifying the repo for demos, I believe I made a mistake in the code that loads a checkpoint.
I've updated the code. Would you please pull the repo and run it again?

**Comment by 1180300419** [comment]
Thank you so much!
