### ISSUE TITLE
frame_num in other benchmark models

### ISSUE THREAD

**Issue by YoungRaeKimm** [codeslake/RefVSR#5]
Thank you for your great work. 
I'm going to reproduce results in Table 2, but I'm confused in some configurations in other models.

1. How did you configure the frame_num in other benchmark models? I guess this hyper-parameter would be important, but there is no information about this in the paper.
2. Why the frame_num of each model is different? It varies from 7 to 13. 

Thank you

**Comment by codeslake** [comment]
> Thank you for your great work. I'm going to reproduce results in Table 2, but I'm confused in some configurations in other models.
> 
> 1. How did you configure the frame_num in other benchmark models? I guess this hyper-parameter would be important, but there is no information about this in the paper.
> 2. Why the frame_num of each model is different? It varies from 7 to 13.
> 
> Thank you

Hi, @YoungRaeKimm.
Thanks for your interest in our work!

1. `frame_num` actually did not affect the final performance that much, as long as it was greater than 5. I guess the model learns to properly propagate temporal features when `frame_num` is greater than 5.
2. The numbers are chosen to max out the GPU memory, which differs by which model you train.
