### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by newtreeaa** [codeslake/RefVSR#8]
Do I just need to download a RealMCVSR.zip file, or do I need to download all five files?

**Comment by codeslake** [comment]
You need to download all files.

**Comment by newtreeaa** [comment]
> You need to download all files.

Hello, can you divide the dataset into 10G files? A file is 50G, and the network speed is too slow to download

**Comment by codeslake** [comment]
I am working on it. Please hang on.

**Comment by codeslake** [comment]
Try [this link](https://postechackr-my.sharepoint.com/:f:/g/personal/junyonglee_postech_ac_kr/EsUplcJTO-tGmIW1h5wPN9cB8GQyua2V0q73LHP4FFnWWQ?e=cIs9BW), thanks.
