### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by newtreeaa** [codeslake/RefVSR#9]
Hello, do low resolution images and reference images have to be the same size in inferenceing? If my reference image is not the same size as the low resolution image, how can I inference?

**Comment by codeslake** [comment]
Hi!

Reference images do not have to be of the same size as low-resolution images.

**Comment by newtreeaa** [comment]
> Hi!
> 
> Reference images do not have to be of the same size as low-resolution images.

I try to inference on this web site https://replicate.com/codeslake/refvsr-cvpr2022.But it requires that reference images have to be of the same size as low-resolution images. Can you provide other inference code?

**Comment by codeslake** [comment]
What is the size of each LR and Ref image?

**Comment by codeslake** [comment]
I will manually check the size issue in my spare time.
I will keep updating it in this thread.
Closing the issue.
